services:
  frontend:
    build:
      context: ./FrontEnd/LAPManagement
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=GorditoSpider123
      - DATABASE_SERVER=mssql
      - DATABASE=LAPManagement
    depends_on:
      - mssql
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "GorditoSpider123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_server_db:/sqlserver/data
volumes:
  sql_server_db: {}